# Generated by Django 6.0.2 on 2026-02-07 00:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=2000, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=60, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("address1", models.CharField(blank=True, max_length=200, null=True)),
                ("address2", models.CharField(blank=True, max_length=200, null=True)),
                ("zip", models.CharField(default="1111", max_length=20)),
                ("newsletter", models.BooleanField(default=True)),
                ("instructor", models.BooleanField(default=False)),
                (
                    "profile_pic",
                    django_resized.forms.ResizedImageField(
                        crop=["middle", "center"],
                        default="default-profile.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[300, 300],
                        upload_to="profile/%Y/%m/%d/",
                    ),
                ),
                ("facebook", models.URLField(default="https://facebook.com/", max_length=350)),
                ("instagram", models.URLField(default="https://instagram.com/", max_length=350)),
                ("linkedin", models.URLField(default="https://linkedin.com/in/", max_length=350)),
                ("github", models.URLField(default="https://github.com/", max_length=350)),
                ("registered", models.BooleanField(default=False)),
                ("occupation", models.CharField(default="Awesome Hacker", max_length=500)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
