# Generated by Django 6.0.2 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0002_alter_usermodel_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=5,
            ),
        ),
    ]
