# Generated by Django 6.0 on 2026-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_usermodel_theme_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('analysis_type', models.CharField(choices=[('phonetic', 'Phonetic'), ('linguistic', 'Linguistic')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
